name: Quantum Santa Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        ref: main

    - name: Set up Git
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
    - name: Check for detached HEAD and create branch if necessary
      run: |
        if [ "$(git rev-parse --abbrev-ref HEAD)" = "HEAD" ]; then
          git switch -c temp-branch
        fi
        pip install sqlite3 jq

    - name: Run methodology script
      run: |
        chmod +x methodology.sh
        ./methodology.sh

    - name: Run database script
      run: |
        python make_sqlite_database.py outputs
    - name: Push changes to new branch
      run: |
        git commit -am "Automated changes by GitHub Actions"
        git push origin HEAD:$(git rev-parse --abbrev-ref HEAD) || echo "Push failed"
        if [ "$(git rev-parse --abbrev-ref HEAD)" = "HEAD" ]; then
          echo "Error: Still in detached HEAD state"
          exit 1
        fi
