name: Quantum Santa Workflow

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Checkout branch
      uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}
        fetch-depth: 0

    - name: Set up Git user
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@users.noreply.github.com"
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install sqlite3 jq

    - name: Run methodology script
      run: |
        chmod +x methodology.sh
        ./methodology.sh

    - name: Run database script
      run: |
        python make_sqlite_database.py outputs
    - name: Verify Git configuration
    - name: Check for detached HEAD and create branch if necessary
      run: |
        if [ "$(git rev-parse --abbrev-ref HEAD)" = "HEAD" ]; then
          branch_name="gha-fix-$(date +%s)"
          git switch -c $branch_name
        fi
        chmod +x methodology.sh
        ./methodology.sh

    - name: Run database script
      run: |
        python make_sqlite_database.py outputs
    - name: Verify Git configuration
      run: |
        git config --list || echo "Failed to list git config"
    - name: Set up Git
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@users.noreply.github.com"
