name: Run make_sqlite_database

on:
  push:
  pull_request:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run make_sqlite_database script
      run: python make_sqlite_database.py outputs/
    - name: Run worldmap script
      run: python worldmap.py
    - name: Commit and push worldmap.png
      run: |
        git config --global user.name "github-actions"
    - name: Checkout branch
      run: |
        git fetch origin
        git checkout ${{ github.ref }}
        git config --global user.email "github-actions@github.com"
        git add worldmap.png
        git commit -m "Add generated worldmap.png"
        git push
