name: Run make_sqlite_database

on:
  push:
  pull_request:
    paths:
      - 'make_sqlite_database.py'
      - 'worldmap.py'
      - 'outputs/*.json'
      - '.github/workflows/run_script.yml'

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v2
